### ISSUE TITLE
DX crash?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#129]
I do have bunch of tabs open in Chrome but never had this happen before...

```

2022-08-01 05:02:27,003 [1] ERROR AG.GameProject.ATC.Program - [SaveScreen] Error parsing savegame: saves\1_0 beta2.zip
2022-08-01 05:02:27,003 [1] ERROR AG.GameProject.ATC.Program - ------------------- 
HRESULT: [0x8007000E], Module: [General], ApiCode: [E_OUTOFMEMORY/Out of memory], Message: Not enough memory resources are available to complete this operation.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateTexture()
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D.GenerateIfRequired()
   at AG.Components.TiledScene.BuildTileMap()
   at AG.GameProject.ATC.SRLScene.Compile(Boolean dotilemap)
   at AG.GameProject.ATC.SRLSaveSystem.LoadSRLScene(SRLScene scene, SRLSceneData data)
   at AG.GameProject.ATC.SRLSaveSystem.LoadScene(AGBaseScene scene, BaseSceneData data)
   at AG.Components.SaveSystem`1.LoadGameFromData(AGBaseGame pGame, TWorldData pData)
   at AG.GameProject.ATC.SRLSaveSystem.LoadGameFromFile(AGBaseGame pGame, String pFile)
   at AG.GameProject.ATC.LoadingScene.Update(GameTime gameTime)
 -------------------
```

**Comment by IvanBajlo** [comment]
these two seems to have generated in game folder

[NBug.log](https://github.com/AnarkisGaming/ATC-Feedback/files/9230577/NBug.log)
[specs.txt](https://github.com/AnarkisGaming/ATC-Feedback/files/9230578/specs.txt)

**Comment by SerialKicked** [comment]
Well, it's definitely the graphic card running out of memory, the reason why, tho. Not sure. I'll have a look to make sure i didn't leave unused textures data in memory. Thanks
